### ISSUE TITLE
Issues with electron+noderify

### ISSUE THREAD

**Issue by heapwolf** [Level/multileveldown#8]
After my code is packaged up with noderify and placed into electron, [`__dirname`](https://github.com/mafintosh/multileveldown/blob/43f894a82a63624ea2c57524f8e88ad0d4c33222/messages.js#L4) becomes `/`, then `/node_modules/multileveldown/schema.proto` is the path. Any ideas how this might be worked around? /cc @dominictarr

**Comment by dominictarr** [comment]
@0x00A we need to add [brfs](https://github.com/substack/brfs) into noderify

**Comment by 0x00A** [comment]
that makes sense, do you have any ideas on how you want to go about doing that?

**Comment by dominictarr** [comment]
brfs [returns a transform stream](https://github.com/substack/brfs#var-tr--brfsfile-opts)
so I think we can just drop it into the pipeline [after resolving dependencies](https://github.com/dominictarr/noderify/blob/master/index.js#L158)

**Comment by 0x00A** [comment]
This would be a huge win for projects using noderify to boost performance/load-time :)

**Comment by dominictarr** [comment]
ah... looks the way browserify transforms have changed a lot since I last
used them... so it's not gonna be as simple as I thought
